# Place this in ~/.config/river/planarwm.conf

window {
  force_ssd = true
  wallpaper_path = "/home/friday/.config/walls/tiledsmallskull.jpg"
  # wallpaper_path = "/home/friday/.config/walls/Tiled Desktop Wallpaper Group.png"
}
bindings {
  # use "shell <command>" to run command
  none.XF86AudioMute = "shell pactl set-sink-mute @DEFAULT_SINK@ toggle"
  none.XF86AudioLowerVolume = "shell pactl set-sink-volume @DEFAULT_SINK@ -3%"
  none.XF86AudioRaiseVolume = "shell pactl set-sink-volume @DEFAULT_SINK@ +3%"
  none.XF86AudioMicMute = "shell pactl set-source-mute @DEFAULT_SOURCE@ toggle"
  none.XF86MonBrightnessDown = "shell brightnessctl set 5%-"
  none.XF86MonBrightnessUp = "shell brightnessctl set 5%+"
  none.XF86AudioPlay = "shell playerctl play-pause"
  none.XF86AudioNext = "shell playerctl next"
  none.XF86AudioPrev = "shell playerctl previous"
  none.Print = "shell grim -g \"$(slurp)\" - | wl-copy"
  shift.Print = "shell filename=~/Pictures/Screenshots/$(date +\"%F_%Hh%Mm%Ss\").png && grim \"$filename\" && wl-copy < \"$filename\""
  alt.0 = "shell killall planarwm redshift dunst kanshi quickshell swayidle; planarwm"
  alt.m = "shell swaylock -f -c 4e6f6f"

  # use "spawn <program>" to spawn program
  alt.t = "spawn foot"
  alt.r = "spawn wmenu-run -bip(｡•̀ᴗ-)✧"
  alt.b = "spawn firefox"
  alt-shift.b = "spawn firefox --private-window"
  alt.space = "spawn qs ipc call panel toggle"

  # window control
  alt.j = "next_slide"
  alt.k = "prev_slide"
  alt-shift.j = "moveto_next_slide"
  alt-shift.k = "moveto_prev_slide"
  alt.h = "prev_window"
  alt.l = "next_window"
  alt-shift.h = "moveto_prev_window"
  alt-shift.l = "moveto_next_window"
  alt.n = "cycle_tiling"
  alt.f = "fullscreen"
  alt-shift.f = "center_focused"
  alt.grave = "close"
  alt-shift.m = "exit"
  ctrl-alt-shift.m = "shell systemctl poweroff"
  alt.y = "toggle_overview"
}

# run these commands as shell on startup
startup = [
  "dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=planarwm;systemctl --user restart xdg-desktop-portal; systemctl --user restart xdg-desktop-portal-wlr; systemctl --user restart xdg-desktop-portal-gtk;"
  "kanshi"
  # "dunst"
  "quickshell"
  # "~/.config/scripts/randwall.sh"
  "swayidle -w timeout 600 'swaylock -f -c 4E6F6F' timeout 900 'systemctl hybrid-sleep' before-sleep 'swaylock -f -c AE6F6F'"
  "redshift -O 5000"
  "env -a batteryscript fish /home/friday/.config/scripts/battery.fish"
  "thunderbird"
]
